//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ftc_projectEntities : DbContext
    {
        public ftc_projectEntities()
            : base("name=ftc_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_all> data_all { get; set; }
        public virtual DbSet<data_position_info> data_position_info { get; set; }
        public virtual DbSet<data_path> data_path { get; set; }
        public virtual DbSet<settings_configure> settings_configure { get; set; }
        public virtual DbSet<settings_position> settings_position { get; set; }
        public virtual DbSet<fuzzy_label> fuzzy_label { get; set; }
        public virtual DbSet<fuzzy_membership> fuzzy_membership { get; set; }
    }
}
